GET /{path? ~ ^(?!admin).*} as home uses guest: HomeController@index

GET /checkToken2 as checkToken2 uses api;guest: UserController@checkToken2

GET /checkToken3 as checkToken3:
  controller: UserController
  action: checkToken3
  middleware: api,guest

POST /save uses auth: ArticleController@save

PUT /saveAll uses auth: ArticleController@save

/api uses api:
  GET /entity: EntityController@list
  GET /entity/{id ~ \d+}  : EntityController@get
  POST /entity/{id ~ \d+} : EntityController@save

  GET /entity/{id}/getComments:
    action: EntityController@getComments

  /admin:
    GET /index              : AdminController@index
    GET /entity/{id ~ \d+}  : AdminController@entity
    /subroute3:
      GET /entity/{id ~ \d+}: AdminController@entity
      GET /data/{alias ~ .+}: AdminController@entity

  /admin123/{section ~ \w+}:
    GET /index: AdminSectionController@index

/sub as sub1 uses api:
  +: ~import sub.yaml

GET /api/model/export.{format ~ \w+}: ModelController@export

/included-route as parent:
  GET /index/{id ~ \d+} as .myIndex: IncludedController@index
